### ISSUE TITLE
crash when not caching buddy icon.

### ISSUE THREAD

**Issue by xiehuc** [kagesenshi/gnome-shell-extensions-pidgin#31]
when i use
purple_buddy_icons_set_caching(0);
it will crash.
if 0 changed to 1.it is ok.
notice purple_buddy_icon_get_full_path_DBUS.
well we do not have path of icon.
ps:
gdb:
Program received signal SIGABRT, Aborted.
0x00007ffff45ff445 in __GI_raise (sig=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
64  ../nptl/sysdeps/unix/sysv/linux/raise.c: 没有那个文件或目录.
(gdb) bt
#0  0x00007ffff45ff445 in __GI_raise (sig=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#1  0x00007ffff4602bab in __GI_abort () at abort.c:91
#2  0x00007ffff463ce2e in __libc_message (do_abort=2, fmt=0x7ffff47450d0 "**\* glibc detected **\* %s: %s: 0x%s ***\n")

```
at ../sysdeps/unix/sysv/linux/libc_fatal.c:201
```
#3  0x00007ffff4647626 in malloc_printerr (action=3, str=0x7ffff4742081 "free(): invalid pointer", ptr=<optimized out>)

```
at malloc.c:5007
```
#4  0x00007ffff4d4948c in purple_buddy_icon_get_full_path_DBUS (message_DBUS=0x5555564a8aa0, error_DBUS=0x7fffffffb730)

```
at ./dbus-bindings.c:3316
```
#5  0x00007ffff4d334ae in purple_dbus_dispatch_cb (user_data=<optimized out>, message=0x5555564a8aa0, connection=0x555555921b00)

```
at /build/buildd/pidgin-2.10.3/./libpurple/dbus-server.c:458
```
#6  purple_dbus_dispatch_cb (connection=0x555555921b00, message=0x5555564a8aa0, user_data=<optimized out>)

```
at /build/buildd/pidgin-2.10.3/./libpurple/dbus-server.c:430
```
#7  0x00007ffff4d13145 in purple_marshal_BOOLEAN__POINTER_POINTER (cb=<optimized out>, args=<optimized out>, data=<optimized out>,

```
return_val=0x7fffffffb7a8) at /build/buildd/pidgin-2.10.3/./libpurple/signals.c:876
```
#8  0x00007ffff4d12296 in purple_signal_emit_vargs_return_1 (instance=<optimized out>, signal=<optimized out>, args=0x7fffffffb7d8)

```
at /build/buildd/pidgin-2.10.3/./libpurple/signals.c:563
```
#9  0x00007ffff4d123d1 in purple_signal_emit_return_1 (instance=<optimized out>, signal=<optimized out>)

```
at /build/buildd/pidgin-2.10.3/./libpurple/signals.c:506
```
#10 0x00007ffff4d55b92 in purple_dbus_dispatch (connection=0x555555921b00, message=0x5555564a8aa0, user_data=<optimized out>)

```
at /build/buildd/pidgin-2.10.3/./libpurple/dbus-server.c:569
```
#11 0x00007ffff7bb2b01 in ?? () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#12 0x00007ffff7ba49f0 in dbus_connection_dispatch () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#13 0x00007ffff0658425 in ?? () from /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2
#14 0x00007ffff4ff9d53 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff4ffa0a0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff4ffa49a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff62252f7 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#18 0x000055555558f1fe in main (argc=1, argv=0x7fffffffe038) at /build/buildd/pidgin-2.10.3/./pidgin/gtkmain.c:933

**Comment by notsyncing** [comment]
tried the newest git pull. problem still exists.
with fedora 17 x86_64, pidgin 2.10.5-1.fc17 (libpurple 2.10.5), gnome-shell 3.4.1-6.fc17, dbus 1.4.10-6.fc17
